project:
  type: website

website:
  title: "IQB Methods Team"
  site-url: https://iqb-research.github.io/IQB-Methods/
  page-navigation: true
  open-graph: true
  repo-url: https://github.com/IQB-Methods
  repo-actions: [edit, issue]
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: posts_r_sig.qmd
        text: R-Sig
      - href: posts_newsletter.qmd
        text: Newsletter
    right:
      - icon: rss
      - href: index.xml

  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "R Tutorials"
        contents:
          - docs/R/index.qmd
          - docs/R/ws1.qmd
          - docs/R/ws2.qmd
          - docs/R/ws3.qmd
          - section: "Cheat Sheets"
            contents:
             - href: https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf
               text: Base R
      - section: "Reproducibility"
        contents:
          - docs/reproduce/renv.qmd
      - section: "eat Packages"
        contents: 
          - docs/eatPackages/index.qmd
          - docs/eatPackages/eatPrep.qmd
          - docs/eatPackages/eatModel.qmd
          - docs/eatPackages/eatRep.qmd
          - docs/eatPackages/eatGADS.qmd
          - docs/eatPackages/eatTools.qmd
          - docs/eatPackages/eatAnalysis.qmd
          - docs/eatPackages/eatATA.qmd
          - docs/eatPackages/eatFDZ.qmd
          - docs/eatPackages/eatCodebook.qmd
          - docs/eatPackages/eatRecode.qmd
          - docs/eatPackages/eatPlot.qmd
      - section: "Quarto"
        contents: 
          - docs/quarto/index.qmd
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

